  var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                      xxxxxxxx  ",
   "  x                                                                   x      x  ",
   "  x                                                 y                 x      x  ",
   "  x                                                                   x      x  ",
   "  x          xxxx                       xxxxxx      x                 x      x  ",
   "  x  @       x  x      y                x    x      x                 x      x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxx    xx    xxx     xxxxxxx    x      x  ",
   "                              x   x           x    x x     x     x!!!!          ",
   "                              x!!!x           x!!!!x x!!!!!x                    ",
   "                              x!!!x           x!!!!x x!!!!!x                    ",
   "                              xxxxx           xxxxxx xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],